[project]
name = "libraymanagement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "flask-mail>=0.10.0",
    "mysql-connector-python>=9.2.0",
    "pillow>=11.1.0",
    "requests>=2.32.3",
]
